name: rajnikant
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Download Ngrok
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract Ngrok File
      run: Expand-Archive ngrok.zip -DestinationPath .\ngrok
    - name: Connect Ngrok
      run: .\ngrok\ngrok.exe authtoken 2jMIMDy4cWyZ0rWm9mzeDJUEQN0_5z4SJN3g9mrHhKoLHE4CA
    - name: Windows10 RDP Configuration
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user rajnikant Password123 /add
        net localgroup administrators rajnikant /add
        net user rajnikant /active:yes
    - name: Start Ngrok Tunnel
      run: .\ngrok\ngrok.exe tcp 3389 > ngrok_log.txt &
    - name: Save Ngrok URL to Text
      shell: pwsh
      run: |
        Start-Sleep -Seconds 10
        $ngrokUrl = (Get-Content ngrok_log.txt) -match 'url=(.*)' | Out-Null; $matches[1] | Out-File -FilePath ngrok_url.txt
    - name: Display Ngrok URL
      run: type ngrok_url.txt
    - name: Run Ping Loop
      run: |
        @echo off
        :LOOP
        ping -n 2 127.0.0.1 >nul
        goto LOOP
