name: rajnikant
on:
  workflow_dispatch:

jobs:
  setup_remote_access:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install Ngrok via Chocolatey
      run: choco install ngrok -y
    - name: Connect Ngrok
      run: ngrok authtoken 2jMIMDy4cWyZ0rWm9mzeDJUEQN0_5z4SJN3g9mrHhKoLHE4CA
    - name: Configure Windows RDP
      run: |
        echo "Configuring Windows RDP..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user rajnikant P@ssw0rd123! /add
        net localgroup administrators rajnikant /add
        net user rajnikant /active:yes
        net accounts /minpwlen:8 /maxpwage:unlimited /uniquepw:5
    - name: Start Ngrok to expose RDP
      run: |
        echo "Starting Ngrok to expose RDP..."
        ngrok tcp 3389 --region=us > ngrok_output.log &
        sleep 10
    - name: Display Ngrok URL
      run: cat ngrok_output.log
    - name: Keep Session Alive and Display Ngrok URL
      shell: pwsh
      run: |
        while ($true) {
          ping -n 1 127.0.0.1 > $null
          cat ngrok_output.log
          Start-Sleep -Milliseconds 500
        }
