name: rajnikant
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install localtunnel
      run: npm install -g localtunnel
    - name: Windows10 RDP Configuration
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user rajnikant P@ssw0rd123! /add
        net localgroup administrators rajnikant /add
        net user rajnikant /active:yes
        net accounts /minpwlen:8 /maxpwage:unlimited /uniquepw:5
    - name: Start localtunnel
      run: lt --port 3389 --subdomain rajnikantrdp > localtunnel_log.txt &
    - name: Display localtunnel URL
      run: type localtunnel_log.txt
    - name: Run Ping Loop
      run: |
        @echo off
        :LOOP
        ping -n 2 127.0.0.1 >nul
        goto LOOP
