name: rajnikant
on:
  workflow_dispatch:

jobs:
  setup_remote_access:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install Hypertunnel
      run: npm install -g hypertunnel
    - name: Generate Random Tunnel Name
      id: generate_tunnel_name
      run: echo "::set-output name=tunnel_name::$(openssl rand -hex 6)"
    - name: Configure Windows RDP
      run: |
        echo "Configuring Windows RDP..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user rajnikant P@ssw0rd123! /add
        net localgroup administrators rajnikant /add
        net user rajnikant /active:yes
        net accounts /minpwlen:8 /maxpwage:unlimited /uniquepw:5
    - name: Start Hypertunnel to expose RDP
      run: |
        echo "Starting Hypertunnel to expose RDP..."
        hypertunnel --port 3389 --name ${{ steps.generate_tunnel_name.outputs.tunnel_name }} > tunnel_output.log &
        sleep 10
        cat tunnel_output.log
    - name: Keep Session Alive
      run: sleep infinity
