name: rajnikant
on:
  workflow_dispatch:

jobs:
  setup_remote_access:
    runs-on: windows-latest
    timeout-minutes: 9999
    steps:
    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
    - name: Install Google Chrome
      run: choco install googlechrome -y
    - name: Install Python
      run: choco install python -y
    - name: Install PageKite
      run: pip install pagekite
    - name: Configure Windows RDP
      run: |
        echo "Configuring Windows RDP..."
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        net user rajnikant P@ssw0rd123! /add
        net localgroup administrators rajnikant /add
        net user rajnikant /active:yes
        net accounts /minpwlen:8 /maxpwage:unlimited /uniquepw:5
    - name: Start PageKite to expose RDP
      run: |
        echo "Starting PageKite to expose RDP..."
        pagekite.py 3389 okbkckdkab.pagekite.me > pagekite_log.txt &
    - name: Display PageKite log
      run: |
        echo "Displaying PageKite log..."
        Start-Sleep -Seconds 10
        type pagekite_log.txt
    - name: Run Ping Loop
      run: |
        echo "Starting ping loop to keep the session alive..."
        @echo off
        :LOOP
        ping -n 2 127.0.0.1 >nul
        goto LOOP
